services:
  solid:
    image: solidproject/community-server:7
    ports:
      - 3000:3000
    environment:
      CSS_LOGGING_LEVEL: info
      CSS_CONFIG: /tmp/config.json
      CSS_PORT: 3000
    volumes:
      - ./server-config.json:/tmp/config.json:ro
      - ./../out-fragments/http/localhost_3000:/data:ro
  sparql:
    build:
      context: .
      network: host
      dockerfile: comunica.dockerfile
    entrypoint: node ./bin/http.js
    command: --context /tmp/context.json --port 3001 --timeout 30
    ports:
      - 3001:3001
    volumes:
      - ./../out-fragments/http/localhost_3001/data.nq:/opt/client/data.nq:ro
      - ./engine-context.json:/tmp/context.json:ro
